CONFIG_FLASH=y

CONFIG_LOG=y
CONFIG_FS_LOG_LEVEL_DBG=y

CONFIG_HEAP_MEM_POOL_SIZE=16384

CONFIG_SHELL=y
CONFIG_SHELL_LOG_LEVEL_DBG=y

CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_SHELL=y
CONFIG_FILE_SYSTEM_LITTLEFS=y

CONFIG_FLASH_MAP=y

CONFIG_SETTINGS=y 

CONFIG_SETTINGS_SHELL=y
CONFIG_SETTINGS_RUNTIME=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_SETTINGS_FILE=y
#CONFIG_NVS=y
#CONFIG_SETTINGS_NVS=y

CONFIG_HEAP_MEM_POOL_SIZE=16384

