#######################
# Base Configuration 
#######################

#CONFIG_INIT_STACKS=y
#CONFIG_THREAD_STACK_INFO=y
#CONFIG_THREAD_MONITOR=y
CONFIG_BOOT_BANNER=n
#CONFIG_THREAD_NAME=y
#CONFIG_THREAD_RUNTIME_STATS=y
#CONFIG_THREAD_RUNTIME_STATS_USE_TIMING_FUNCTIONS=y
CONFIG_STATS=y

# POSIX_TIMERS requires an embedded C library while the native USB driver is incompatible with it.
# So let's disable it. Once USB_NATIVE_POSIX supports embedded C libraries this can be removed.
CONFIG_POSIX_API=n
CONFIG_POSIX_TIMERS=n
#CONFIG_POSIX_SYSTEM_INTERFACES=y

CONFIG_GPIO=y
CONFIG_CRC=y 
CONFIG_W1=y 
#CONFIG_SYMTAB=y 
CONFIG_SENSOR=y 
#CONFIG_LED=y 

CONFIG_HWINFO=y
#CONFIG_EEPROM=y
#CONFIG_UUID=y

CONFIG_SIZE_OPTIMIZATIONS_AGGRESSIVE=y
CONFIG_LEGACY_GENERATED_INCLUDE_PATH=y
CONFIG_ASSERT_VERBOSE=y
CONFIG_COMPILER_SAVE_TEMPS=y
CONFIG_OUTPUT_PRINT_MEMORY_USAGE=y
CONFIG_BUILD_OUTPUT_META=y
CONFIG_OUTPUT_STAT=y
CONFIG_OUTPUT_SYMBOLS=y
CONFIG_CLEANUP_INTERMEDIATE_FILES=n
CONFIG_BUILD_OUTPUT_STRIP_PATHS=y
CONFIG_CHECK_INIT_PRIORITIES=y
CONFIG_DEBUG=y

#CONFIG_INSTRUMENTATION=y
#CONFIG_INSTRUMENTATION_MODE_CALLGRAPH=y    # For tracing
#CONFIG_INSTRUMENTATION_MODE_STATISTICAL=y  # For profiling

# Kernel options
CONFIG_MAIN_STACK_SIZE=2048

CONFIG_APP_FULL_BINDESC=y


CONFIG_CONSOLE=y
CONFIG_CONSOLE_SUBSYS=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE_HANDLER=y
CONFIG_CONSOLE_GETCHAR=y
CONFIG_CONSOLE_GETLINE=n
