#######################
# Logging Configuration 
#######################
CONFIG_LOG=y
CONFIG_LOG_CMDS=y
CONFIG_PRINTK=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_BACKEND_UART=y
# CONFIG_GPIO_LOG_LEVEL_DBG=y
# CONFIG_SPI_LOG_LEVEL_INF=y
