# USB CDC ECM (Ethernet over USB)
CONFIG_USB_DEVICE_NETWORK_ECM=y
#CONFIG_USB_DEVICE_NETWORK_NCM=y

# Networking
#CONFIG_NET_CONNECTION_MANAGER=y
#CONFIG_CTR_DRBG_CSPRNG_GENERATOR


# WebSocket
CONFIG_WEBSOCKET_CLIENT=n
CONFIG_HTTP_PARSER=n
CONFIG_HTTP_PARSER_URL=n

# Network Buffers
CONFIG_NET_PKT_RX_COUNT=16
CONFIG_NET_PKT_TX_COUNT=16
CONFIG_NET_BUF_RX_COUNT=32
CONFIG_NET_BUF_TX_COUNT=32
CONFIG_NET_MAX_CONTEXTS=10


CONFIG_NET_L2_ETHERNET=y
# General config
CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_MAIN_STACK_SIZE=1200

# Networking config
# Network address config
CONFIG_SHELL_BACKEND_TELNET=y
CONFIG_NET_SHELL=y

# Logging
CONFIG_NET_LOG=y
CONFIG_POLL=y



CONFIG_NET_L2_ETHERNET=y
# General config
CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_MAIN_STACK_SIZE=1200

# Networking config
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_TCP=y
CONFIG_NET_ICMPV4_ACCEPT_BROADCAST=y
CONFIG_NET_SOCKETS=y
CONFIG_ZVFS_POLL_MAX=5


# Network driver config
CONFIG_TEST_RANDOM_GENERATOR=y
# Network address config
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_NEED_IPV6=n
CONFIG_NET_CONFIG_AUTO_INIT=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.0.2.2"
#CONFIG_NET_CONFIG_MY_IPV6_ADDR="2001:db8::1"
#CONFIG_NET_CONFIG_PEER_IPV6_ADDR="2001:db8::2"


