#######################
# Shell Configuration 
#######################
CONFIG_SHELL=y
CONFIG_SHELL_MINIMAL=n 
CONFIG_SHELL_CMDS_SELECT=y
CONFIG_SHELL_START_OBSCURED=n
CONFIG_SHELL_LOG_BACKEND=n
CONFIG_SHELL_BACKEND_SERIAL_CHECK_DTR=n


# allow separate shell + console UART devices
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_BACKEND_SERIAL_CHECK_DTR=n
CONFIG_SHELL_BACKEND_SERIAL_INTERRUPT_DRIVEN=y


#CONFIG_ADC_SHELL=y
#CONFIG_GPIO_SHELL=y
CONFIG_KERNEL_SHELL=y
CONFIG_DEVICE_SHELL=y
CONFIG_DATE_SHELL=y

CONFIG_STATS_SHELL=y
#CONFIG_INPUT_SHELL=y

#CONFIG_SYMTAB_SHELL=y
#CONFIG_UPDATEHUB_SHELL=y
#CONFIG_HAWKBIT_SHELL=y

#CONFIG_CRC_SHELL=y
#CONFIG_ZTEST_SHELL=y
#CONFIG_PSA_SHELL=y
#CONFIG_MBED_TLS_SHELL=y
CONFIG_ISR_TABLE_SHELL=y
#CONFIG_OPENTHREAD_SHELL=y
#CONFIG_LV_Z_SHELL=y
#CONFIG_POSIX_SHELL=y
#CONFIG_RTC_SHELL=y
#CONFIG_VIDEO_SHELL=y
#CONFIG_I2C_SHELL=y
#CONFIG_I3C_SHELL=y
#CONFIG_CAN_SHELL=y
#CONFIG_W1_SHELL=y
CONFIG_SENSOR_SHELL=y
#CONFIG_USBC_TCPC_SHELL=y
#CONFIG_USBC_PPC_SHELL=y
#CONFIG_SENSOR_SHELL_BATTERY=y
#CONFIG_EDAC_SHELL=y
#CONFIG_DAC_SHELL=y
#CONFIG_WDT_SHELL=y
#CONFIG_PWM_SHELL=y
#CONFIG_LED_SHELL=y
#CONFIG_COMPARATOR_SHELL=y
CONFIG_HWINFO_SHELL=y
#CONFIG_REGULATOR_SHELL=y
#CONFIG_UART_SHELL=y
#CONFIG_EEPROM_SHELL=y
#CONFIG_PCIE_SHELL=y
#CONFIG_FPGA_SHELL=y
#CONFIG_COUNTER_SHELL=y
#CONFIG_PSCI_SHELL=y
#CONFIG_HAPTICS_SHELL=y
#CONFIG_STATS_SHELL=y


#CONFIG_POSIX_ENV_SHELL=y
#CONFIG_POSIX_UNAME_SHELL=y
CONFIG_SHELL=y


# Flash
CONFIG_FLASH=y
CONFIG_STREAM_FLASH=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NONE=n
CONFIG_SETTINGS_RETENTION=y
CONFIG_SETTINGS_FILE=y
CONFIG_SETTINGS_RUNTIME=y
CONFIG_SETTINGS_SHELL=y

CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_SHELL=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_SHELL_TEST_COMMANDS=y
CONFIG_FILE_SYSTEM_SHELL_LS_SIZE=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FS_LITTLEFS_FMP_DEV=y


CONFIG_HWINFO_SHELL=y
CONFIG_STREAM_FLASH_PROGRESS=n
CONFIG_STREAM_FLASH_INSPECT=y
CONFIG_STREAM_FLASH_ERASE=y

CONFIG_FLASH_MAP=y
CONFIG_FLASH_SHELL=y
CONFIG_FLASH_SHELL_TEST_COMMANDS=y


CONFIG_DEVICE_SHELL=y
CONFIG_DEVMEM_SHELL=y
#CONFIG_NET_SHELL=y
CONFIG_APP_VERSION_SHELL=y
CONFIG_SHELL_DEVICE_HELPERS=y
CONFIG_KERNEL_SHELL_PANIC_CMD=y
