#######################
# SPI Configuration 
#######################

CONFIG_SPI=y 
CONFIG_SPI_ASYNC=y

CONFIG_BOOT_BANNER=y
CONFIG_SPI_LOG_LEVEL_INF=y
CONFIG_SPI_SHELL=y
CONFIG_DMA=y
CONFIG_SPI_RTIO=y
