#######################
# USB Configuration 
#######################

#CONFIG_USB_DEVICE_STACK_NEXT=y
#CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
 # Raspberry Pi
CONFIG_USB_DEVICE_VID=0x2E8A
CONFIG_USB_DEVICE_PID=0x0009
#CONFIG_USB_DEVICE_DFU_PID
#CONFIG_USB_DEVICE_SN

# Raspberry Pi
#CONFIG_CDC_ACM_SERIAL_VID=0x2E8A
 # Raspberry Pi Pico SDK CDC UART
#CONFIG_CDC_ACM_SERIAL_PID=0x0009
# CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="CDC UART"
CONFIG_USB_DEVICE_PRODUCT="Zephyr Device Product"
CONFIG_USB_DEVICE_MANUFACTURER="Maskset"
CONFIG_USB_DEVICE_STACK=y
#CONFIG_USB_DEVICE_STACK_NEXT=y

CONFIG_USB_CDC_ACM_LOG_LEVEL_OFF=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y

#CONFIG_USBC_TCPC_DRIVER=y
#CONFIG_USBC_PPC_DRIVER=y


#######################
# USB DFU Configuration 
#######################
#CONFIG_USB_DEVICE_DFU_PID=0x000f
#CONFIG_USB_DEVICE_DFU_PID=0xffff
#CONFIG_USB_DFU_PERMANENT_DOWNLOAD=y
#CONFIG_USB_DFU_WILL_DETACH=y
#CONFIG_USB_DFU_REBOOT=y
#CONFIG_USB_DFU_ENABLE_UPLOAD=y

#CONFIG_USB_DEVICE_STACK_NEXT=y
#CONFIG_USBD_DFU=y
#CONFIG_USBD_LOG_LEVEL_WRN=y
#CONFIG_USBD_DFU_LOG_LEVEL_WRN=y
#CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y
##CONFIG_SAMPLE_USBD_PID=0x0005
#CONFIG_DISK_ACCESS=y
