#######################
# Base Configuration 
#######################

CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_MONITOR=y
CONFIG_BOOT_BANNER=n
CONFIG_THREAD_NAME=y
CONFIG_POSIX_API=y
CONFIG_POSIX_TIMERS=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_THREAD_RUNTIME_STATS_USE_TIMING_FUNCTIONS=y
CONFIG_STATS=y

# POSIX_TIMERS requires an embedded C library while the native USB driver is incompatible with it.
# So let's disable it. Once USB_NATIVE_POSIX supports embedded C libraries this can be removed.
CONFIG_POSIX_API=n
CONFIG_POSIX_TIMERS=n

CONFIG_GPIO=y
CONFIG_SETTINGS=y 
CONFIG_CRC=y 
CONFIG_W1=y 
CONFIG_SYMTAB=y 
#CONFIG_ZTEST=y 
CONFIG_SENSOR=y 
CONFIG_RTC=y 
CONFIG_REGULATOR=y 
CONFIG_LED=y 
#CONFIG_PCIE=y 
CONFIG_DAC=y 
CONFIG_COUNTER=y
CONFIG_COMPARATOR=y 
CONFIG_EDAC=y
#CONFIG_BATTERY=y

CONFIG_SPI=y
CONFIG_PWM=y
CONFIG_HWINFO=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NONE=n
CONFIG_SETTINGS_RUNTIME=y
CONFIG_RESET=y
CONFIG_CONSOLE=y
CONFIG_REBOOT=y
CONFIG_FLASH=y
CONFIG_EEPROM=y
CONFIG_I2C=y
CONFIG_I3C=y
CONFIG_INPUT=y


CONFIG_UUID=y

CONFIG_SIZE_OPTIMIZATIONS_AGGRESSIVE=y
CONFIG_LEGACY_GENERATED_INCLUDE_PATH=y
CONFIG_ASSERT_VERBOSE=y
CONFIG_COMPILER_SAVE_TEMPS=y
CONFIG_OUTPUT_PRINT_MEMORY_USAGE=y
CONFIG_BUILD_OUTPUT_META=y
CONFIG_OUTPUT_STAT=y
CONFIG_OUTPUT_SYMBOLS=y
CONFIG_CLEANUP_INTERMEDIATE_FILES=n
CONFIG_BUILD_OUTPUT_STRIP_PATHS=y
CONFIG_CHECK_INIT_PRIORITIES=y
CONFIG_DEBUG=y
#CONFIG_RETAINED_RAM=y

#CONFIG_INSTRUMENTATION=y
#CONFIG_INSTRUMENTATION_MODE_CALLGRAPH=y    # For tracing
#CONFIG_INSTRUMENTATION_MODE_STATISTICAL=y  # For profiling
CONFIG_POSIX_SYSTEM_INTERFACES=y


# Kernel options
CONFIG_MAIN_STACK_SIZE=2048

