CONFIG_STDOUT_CONSOLE=n
#CONFIG_GLIBCXX_LIBCPP=n

# CONFIG_COMMON_LIBC_REMOVE=n
# CONFIG_EXTERNAL_MODULE_LIBCPP is not set
# CONFIG_CPP_EXCEPTIONS is not set
# CONFIG_CPP_RTTI is not set
#

# CONFIG_FUSE_FS_ACCESS=y

CONFIG_SYMTAB=n
