CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_VID=0x2E8A
CONFIG_USB_DEVICE_PID=0x0009
CONFIG_USB_DEVICE_MANUFACTURER="Maskset"
CONFIG_USB_DEVICE_SN="0123456789ABCDEF"
CONFIG_USB_COMPOSITE_DEVICE=y
CONFIG_USB_CDC_ACM=y

CONFIG_BOOT_USB_DFU_NO=y
CONFIG_BOOT_VALIDATE_SLOT0=y
CONFIG_BOOT_SERIAL_UART=n 
CONFIG_BOOT_SERIAL_CDC_ACM=y
CONFIG_BOOT_MGMT_ECHO=y
CONFIG_ENABLE_MGMT_PERUSER=y
CONFIG_BOOT_MGMT_CUSTOM_STORAGE_ERASE=y

CONFIG_FLASH=y

#if defined(CONFIG_BOOT_SERIAL_ENTRANCE_GPIO) || defined(CONFIG_BOOT_USB_DFU_GPIO) || \
CONFIG_BOOT_SERIAL_ENTRANCE_GPIO=n
CONFIG_BOOT_SERIAL_DETECT_DELAY=0
CONFIG_BOOT_SERIAL_NO_APPLICATION=y
CONFIG_BOOT_SERIAL_IMG_GRP_HASH=y
CONFIG_UPDATEABLE_IMAGE_NUMBER=1
CONFIG_MCUBOOT_SERIAL=y
CONFIG_MCUBOOT_BOOT_BANNER=y
CONFIG_BOOT_BANNER_STRING="Using Zephyr OS build"
CONFIG_MCUBOOT_USE_TLV_ALLOW_LIST=y
CONFIG_MCUBOOT_STORAGE_WITH_ERASE=y
CONFIG_USB_DEVICE_PRODUCT="SMP Bootloader"
CONFIG_SERIAL=y
CONFIG_CONSOLE=n

CONFIG_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_SHELL=y
CONFIG_BOOT_FIRMWARE_LOADER_ENTRANCE_GPIO=n
