# Sysbuild configuration file.

# Enable MCUboot using overwrite only mode for this sample.
#SB_CONFIG_BOOTLOADER_NONE=y
SB_CONFIG_BOOTLOADER_MCUBOOT=y

#SB_CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="bootloader/mcuboot/root-rsa-2048.pem"

SB_CONFIG_BOOT_SIGNATURE_TYPE_NONE=y
SB_CONFIG_MCUBOOT_MODE_SWAP_SCRATCH=n
SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE=y
SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=n 
SB_CONFIG_MCUBOOT_MODE_DIRECT_XIP=n 
SB_CONFIG_MCUBOOT_MODE_DIRECT_XIP_WITH_REVERT=n 
SB_CONFIG_MCUBOOT_MODE_FIRMWARE_UPDATER=n 
SB_CONFIG_MCUBOOT_MODE_SINGLE_APP=n

# SB_CONFIG_MCUBOOT_MODE_RAM_LOAD=y
